spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://127.0.0.1/blog/
      database: blog
      repositories:
        enabled: true
  jade4j:
      caching: true
server:
  error:
    whitelabel:
      enabled: false
  port:
      8080
